### ISSUE TITLE
Downlink CRC failure

### ISSUE THREAD

**Issue by G-MatrixSystems** [sigfox-tech-radio/sigfox-ep-lib#3]
We are busy developing a new Sigfox device using the LR1110. Uplink works without issue. Downlink does not work. I can see that the message is received by the LR1110 and the EP-LIB goes through all the motions until verifying the CRC which fails.

I am pretty sure it is not a signal strength issue. as we have a tower 50 or so meters from our office. Uplink is received at -89dBm outside (antenna is not yet tuned correctly). Received indoor rssi of -106dBm, so I do not think it is a signal problem. But I have no idea what to look for?

**Comment by CedricB31** [comment]
@G-MatrixSystems Your issue may have many reasons. 
The first step to verify your device working in reception would be to test with [RSA tool](https://build.sigfox.com/sdr-dongle#sigfox-radio-signal-analyzer-rsa) and [RF&P addon](https://github.com/sigfox-tech-radio/sigfox-ep-addon-rfp) (test : "DL-Protocol", [test mode F](https://github.com/sigfox-tech-radio/sigfox-ep-addon-rfp/blob/master/inc/sigfox_ep_addon_rfp_api.h#L101)) locally. Don't forget to inform your ID/Key and check "Downlink capable" in RSA's "device configuration" window.

**Comment by G-MatrixSystems** [comment]
> @G-MatrixSystems Your issue may have many reasons. The first step to verify your device working in reception would be to test with [RSA tool](https://build.sigfox.com/sdr-dongle#sigfox-radio-signal-analyzer-rsa) and [RF&P addon](https://github.com/sigfox-tech-radio/sigfox-ep-addon-rfp) (test : "DL-Protocol", [test mode F](https://github.com/sigfox-tech-radio/sigfox-ep-addon-rfp/blob/master/inc/sigfox_ep_addon_rfp_api.h#L101)) locally. Don't forget to inform your ID/Key and check "Downlink capable" in RSA's "device configuration" window.

Thanks. I used RSA tool with the RF&P addon, but it was of no help.

I however think that I found the issue. When setting breakpoints to inspect the received data to compare to what was sent, it suddenly worked.

The problem is not in this (sigfox-ep-lib) library but rather in the LR11XX RF API implementation example (sigfox-ep-rf-api-semtech-lr11xx). In file lr11xx_rf_api.c [on this line](https://github.com/sigfox-tech-radio/sigfox-ep-rf-api-semtech-lr11xx/blob/ba948ff5fedb07531ba3c0c80c7843a10b9ea36f/src/manuf/lr11xx_rf_api.c#L686). If I break the code on this line, and then continue running, lr11xx_radio_pkt_status_gfsk.is_received is true and it works fine. If I do not break on this line, lr11xx_radio_pkt_status_gfsk.is_received is false and it obviously does not work.

**Comment by G-MatrixSystems** [comment]
OK, I finally figured out the issue. Was hardware, the LR1110 Busy pin was not making contact and the library thus did not wait for the LR1110 to be ready before sending the next command.
